export const SEARCH_VIDEOS = 'SEARCH_VIDEOS'
export const GET_VIDEO = 'GET_VIDEO'
export const GET_VIDEO_CLIP = 'GET_VIDEO_CLIP'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
